apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloud-resource-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloud-resource-operator
    app.kubernetes.io/part-of: cloud-resource-operator
  name: cloud-resource-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloud-resource-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cloud-resource-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jkiely-tenant/cloud-resource-operator/cloud-resource-operator@sha256:fc192098edde4e47a0cb3cd887487829ab2d3979501cb13b5ffbf99043134787
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8008
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
